create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text, preferred_language text not null default 'en', created_at timestamptz not null default now());
create table if not exists public.wallets (user_id uuid primary key references auth.users(id) on delete cascade, balance numeric(18,2) not null default 0, currency text not null default 'USD', updated_at timestamptz not null default now());
create table if not exists public.events (id bigint generated by default as identity primary key, sport text not null, league text, home_team text not null, away_team text not null, starts_at timestamptz not null, status text not null default 'scheduled', home_score int not null default 0, away_score int not null default 0);
create table if not exists public.markets (id bigint generated by default as identity primary key, event_id bigint not null references public.events(id) on delete cascade, name text not null, market_type text not null, active boolean not null default true);
create table if not exists public.selections (id bigint generated by default as identity primary key, market_id bigint not null references public.markets(id) on delete cascade, label text not null, odds numeric(10,3) not null, status text not null default 'open');
create table if not exists public.bets (id bigint generated by default as identity primary key, user_id uuid not null references auth.users(id) on delete cascade, bet_type text not null default 'single', stake numeric(18,2) not null, potential_return numeric(18,2) not null default 0, status text not null default 'pending', created_at timestamptz not null default now());
create table if not exists public.bet_selections (id bigint generated by default as identity primary key, bet_id bigint not null references public.bets(id) on delete cascade, selection_id bigint not null references public.selections(id), odds numeric(10,3) not null);

alter table public.profiles enable row level security;
alter table public.wallets enable row level security;
alter table public.bets enable row level security;
alter table public.bet_selections enable row level security;
alter table public.events enable row level security;
alter table public.markets enable row level security;
alter table public.selections enable row level security;

create policy "public can read active events" on public.events for select using (true);
create policy "public can read active markets" on public.markets for select using (active = true);
create policy "public can read open selections" on public.selections for select using (status = 'open');
create policy "users can read own profile" on public.profiles for select using (auth.uid() = id);
create policy "users can update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);
create policy "users can read own wallet" on public.wallets for select using (auth.uid() = user_id);
create policy "users can read own bets" on public.bets for select using (auth.uid() = user_id);
create policy "users can read own bet selections" on public.bet_selections for select using (exists (select 1 from public.bets b where b.id = bet_id and b.user_id = auth.uid()));

-- Service/backend betting writes must be implemented server-side after KYC, jurisdiction,
-- wallet transaction, limits and audit controls are in place.


-- Feed synchronization and odds-engine columns/tables.
alter table public.events add column if not exists provider text, add column if not exists provider_event_id text, add column if not exists provider_sport_key text, add column if not exists provider_league text, add column if not exists last_synced_at timestamptz, add column if not exists live_clock text, add column if not exists live_period text, add column if not exists sync_version bigint not null default 0;
create unique index if not exists events_provider_event_uidx on public.events(provider, provider_event_id) where provider is not null and provider_event_id is not null;
alter table public.markets add column if not exists provider text, add column if not exists provider_market_key text, add column if not exists line numeric(12,3), add column if not exists suspension_reason text, add column if not exists last_synced_at timestamptz;
create unique index if not exists markets_provider_key_uidx on public.markets(event_id, provider, provider_market_key) where provider is not null and provider_market_key is not null;
alter table public.selections add column if not exists provider text, add column if not exists provider_selection_key text, add column if not exists outcome_key text, add column if not exists point numeric(12,3), add column if not exists last_synced_at timestamptz, add column if not exists odds_version bigint not null default 0;
create unique index if not exists selections_provider_key_uidx on public.selections(market_id, provider, provider_selection_key) where provider is not null and provider_selection_key is not null;
create table if not exists public.odds_snapshots (id bigint generated by default as identity primary key, provider text not null, provider_event_id text not null, provider_market_key text not null, provider_selection_key text not null, odds numeric(10,3) not null, point numeric(12,3), bookmaker text, captured_at timestamptz not null default now());
create index if not exists odds_snapshots_event_time_idx on public.odds_snapshots(provider_event_id, captured_at desc);
create table if not exists public.feed_sync_runs (id bigint generated by default as identity primary key, provider text not null, status text not null, sports_requested integer not null default 0, events_seen integer not null default 0, events_upserted integer not null default 0, markets_upserted integer not null default 0, selections_upserted integer not null default 0, errors jsonb not null default '[]'::jsonb, started_at timestamptz not null default now(), finished_at timestamptz);
alter table public.odds_snapshots enable row level security;
alter table public.feed_sync_runs enable row level security;
drop policy if exists "public can read current odds snapshots" on public.odds_snapshots;
create policy "public can read current odds snapshots" on public.odds_snapshots for select using (captured_at > now() - interval '5 minutes');
do $$
begin
  begin alter publication supabase_realtime add table public.events; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.markets; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.selections; exception when duplicate_object then null; end;
end $$;


-- Quote, wallet ledger and settlement foundations.
create unique index if not exists events_provider_event_uidx_full on public.events(provider, provider_event_id);
create unique index if not exists markets_provider_key_uidx_full on public.markets(event_id, provider, provider_market_key);
create unique index if not exists selections_provider_key_uidx_full on public.selections(market_id, provider, provider_selection_key);

create table if not exists public.bet_quotes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  bet_type text not null,
  selection_ids bigint[] not null,
  odds numeric(10,3)[] not null,
  combined_odds numeric(18,6) not null,
  stake numeric(18,2),
  potential_return numeric(18,2),
  status text not null default 'quoted',
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);
alter table public.bet_quotes enable row level security;
drop policy if exists "users can read own quotes" on public.bet_quotes;
create policy "users can read own quotes" on public.bet_quotes for select using (auth.uid() = user_id);

create table if not exists public.wallet_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  bet_id bigint references public.bets(id) on delete set null,
  entry_type text not null,
  amount numeric(18,2) not null,
  currency text not null default 'USD',
  balance_after numeric(18,2),
  reference text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists wallet_ledger_user_time_idx on public.wallet_ledger(user_id, created_at desc);
alter table public.wallet_ledger enable row level security;
drop policy if exists "users can read own wallet ledger" on public.wallet_ledger;
create policy "users can read own wallet ledger" on public.wallet_ledger for select using (auth.uid() = user_id);

alter table public.bets add column if not exists quote_id uuid references public.bet_quotes(id);
alter table public.bets add column if not exists settled_at timestamptz;
alter table public.bets add column if not exists settlement_result text;
alter table public.bets add column if not exists cashout_available boolean not null default false;
