"use client";
import {useEffect,useState} from "react";
import {ChevronLeft,SlidersHorizontal} from "lucide-react";
import {createClient} from "../../../lib/supabase-browser";

export default function Limits(){
 const supabase=createClient(); const [bet,setBet]=useState(""),[week,setWeek]=useState(""),[month,setMonth]=useState(""),[maxStake,setMaxStake]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getUser().then(async({data})=>{if(!data.user){location.href="/login?next=/account/limits";return;}const {data:p}=await supabase.from("profiles").select("betting_limit_daily,betting_limit_weekly,betting_limit_monthly,max_stake").eq("id",data.user.id).maybeSingle();if(p){setBet(p.betting_limit_daily?.toString()||"");setWeek(p.betting_limit_weekly?.toString()||"");setMonth(p.betting_limit_monthly?.toString()||"");setMaxStake(p.max_stake?.toString()||"")}})},[]);
 async function save(e:React.FormEvent){e.preventDefault();setMessage("");setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login?next=/account/limits";return;}const num=(v:string)=>v.trim()===""?null:Number(v);const vals=[num(bet),num(week),num(month),num(maxStake)];if(vals.some(v=>v!==null&&(!Number.isFinite(v)||v<0))){setMessage("Use non-negative numeric limits.");setBusy(false);return;}const {error}=await supabase.from("profiles").update({betting_limit_daily:vals[0],betting_limit_weekly:vals[1],betting_limit_monthly:vals[2],max_stake:vals[3]}).eq("id",user.id);setMessage(error?error.message:"Responsible-gambling limits saved.");setBusy(false)}
 return <main className="app-shell account-page"><header className="topbar"><a className="brand" href="/">BETNOW<span>365</span></a><a className="login-btn" href="/account">Account</a></header><div className="account-wrap"><a className="back-link" href="/account"><ChevronLeft size={18}/> Account</a><section className="account-detail-card"><SlidersHorizontal size={30}/><span className="eyebrow">RESPONSIBLE GAMBLING</span><h1>Limits & controls</h1><p>Set personal limits before real-money features are enabled.</p><form onSubmit={save}><label>Daily betting limit<input value={bet} onChange={e=>setBet(e.target.value)} inputMode="decimal" placeholder="No limit" /></label><label>Weekly betting limit<input value={week} onChange={e=>setWeek(e.target.value)} inputMode="decimal" placeholder="No limit" /></label><label>Monthly betting limit<input value={month} onChange={e=>setMonth(e.target.value)} inputMode="decimal" placeholder="No limit" /></label><label>Maximum stake<input value={maxStake} onChange={e=>setMaxStake(e.target.value)} inputMode="decimal" placeholder="No limit" /></label><button className="place-btn" disabled={busy}>{busy?"Saving…":"Save limits"}</button></form>{message&&<div className="bet-message">{message}</div>}</section></div></main>;
}