"use client";
import {useEffect,useState} from "react";
import {ChevronLeft,FileCheck,ShieldCheck} from "lucide-react";
import {createClient} from "../../../lib/supabase-browser";

export default function Verification(){
 const supabase=createClient();
 const [legalName,setLegalName]=useState(""),[dob,setDob]=useState(""),[country,setCountry]=useState(""),[docType,setDocType]=useState("passport"),[status,setStatus]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getUser().then(async({data})=>{if(!data.user){location.href="/login?next=/account/verification";return;}const {data:v}=await supabase.from("verification_requests").select("status,legal_name,date_of_birth,country,document_type").eq("user_id",data.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(v){setStatus(v.status);setLegalName(v.legal_name||"");setDob(v.date_of_birth||"");setCountry(v.country||"");setDocType(v.document_type||"passport")}})},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setMessage("");if(!legalName.trim()||!dob||!country.trim()||!docType){setMessage("Complete all required fields.");return;}setBusy(true);const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login?next=/account/verification";return;}const {error}=await supabase.from("verification_requests").insert({user_id:user.id,legal_name:legalName.trim(),date_of_birth:dob,country:country.trim(),document_type:docType,status:"pending"});if(error)setMessage(error.message);else{setStatus("pending");setMessage("Verification request submitted. It is now in the admin review queue.");}setBusy(false)}
 return <main className="app-shell account-page"><header className="topbar"><a className="brand" href="/">BETNOW<span>365</span></a><a className="login-btn" href="/account">Account</a></header><div className="account-wrap"><a className="back-link" href="/account"><ChevronLeft size={18}/> Account</a><section className="account-detail-card"><FileCheck size={30}/><span className="eyebrow">VERIFICATION</span><h1>Identity & age verification</h1><p>Complete the information required for identity, age and jurisdiction review. Document upload can be connected to a compliant KYC provider before real-money activation.</p><div className="verification-status"><ShieldCheck size={20}/><span>{status?"Current status: "+status:"Verification required before real-money services"}</span></div><form onSubmit={submit}><label>Legal name<input value={legalName} onChange={e=>setLegalName(e.target.value)} placeholder="As shown on your ID" required /></label><label>Date of birth<input type="date" value={dob} onChange={e=>setDob(e.target.value)} required /></label><label>Country / jurisdiction<input value={country} onChange={e=>setCountry(e.target.value)} placeholder="Country" required /></label><label>Document type<select value={docType} onChange={e=>setDocType(e.target.value)}><option value="passport">Passport</option><option value="national_id">National ID</option><option value="driving_licence">Driving licence</option></select></label><button className="place-btn" disabled={busy}>{busy?"Submitting…":"Submit for review"}</button></form>{message&&<div className="bet-message">{message}</div>}</section></div></main>;
}