"use client";
import {useEffect,useState} from "react";
import {ChevronLeft,Save} from "lucide-react";
import {createClient} from "../../../lib/supabase-browser";

export default function Profile(){
 const supabase=createClient();
 const [email,setEmail]=useState(""),[name,setName]=useState(""),[language,setLanguage]=useState("English"),[currency,setCurrency]=useState("USD"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getUser().then(async({data})=>{if(!data.user){location.href="/login?next=/account/profile";return;}setEmail(data.user.email||"");const {data:p}=await supabase.from("profiles").select("display_name,preferred_language,currency").eq("id",data.user.id).maybeSingle();if(p){setName(p.display_name||"");setLanguage(p.preferred_language||"English");setCurrency(p.currency||"USD")}})},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/login?next=/account/profile";return;}const {error}=await supabase.from("profiles").update({display_name:name.trim()||null,preferred_language:language,currency}).eq("id",user.id);setMessage(error?error.message:"Profile details saved.");setBusy(false)}
 return <main className="app-shell account-page"><header className="topbar"><a className="brand" href="/">BETNOW<span>365</span></a><a className="login-btn" href="/account">Account</a></header><div className="account-wrap"><a className="back-link" href="/account"><ChevronLeft size={18}/> Account</a><section className="account-detail-card"><span className="eyebrow">PROFILE DETAILS</span><h1>Personal details</h1><form onSubmit={save}><label>Account email<input value={email} readOnly /></label><label>Display name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your display name" /></label><label>Language<select value={language} onChange={e=>setLanguage(e.target.value)}><option>English</option><option>বাংলা</option><option>Español</option><option>Deutsch</option><option>Français</option></select></label><label>Account currency<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD</option><option>EUR</option><option>GBP</option></select></label><button className="place-btn" disabled={busy}><Save size={16}/>{busy?"Saving…":"Save profile"}</button></form>{message&&<div className="bet-message">{message}</div>}<small>Identity, age and jurisdiction information is managed separately in Verification.</small></section></div></main>;
}