-- Manual cashier request workflow.
-- User-facing requests never mutate wallets. Authorized back-office/payment
-- operations must verify the request and then write an append-only ledger entry.

create table if not exists public.cashier_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  request_type text not null check (request_type in ('deposit','withdrawal')),
  amount numeric(18,2) not null check (amount > 0),
  currency text not null default 'USD',
  method text not null,
  account_name text,
  account_reference text,
  transaction_reference text,
  note text,
  status text not null default 'pending' check (status in ('pending','under_review','approved','rejected','cancelled','completed')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  completed_at timestamptz,
  rejection_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists cashier_requests_user_time_idx on public.cashier_requests(user_id,created_at desc);
create index if not exists cashier_requests_status_time_idx on public.cashier_requests(status,created_at);
alter table public.cashier_requests enable row level security;

drop policy if exists "users read own cashier requests" on public.cashier_requests;
create policy "users read own cashier requests" on public.cashier_requests
for select to authenticated using (auth.uid()=user_id);

drop policy if exists "users create own cashier requests" on public.cashier_requests;
create policy "users create own cashier requests" on public.cashier_requests
for insert to authenticated with check (auth.uid()=user_id);

revoke update,delete on public.cashier_requests from anon,authenticated;

create or replace function public.set_cashier_updated_at()
returns trigger language plpgsql security invoker set search_path=''
as $$ begin new.updated_at=now(); return new; end; $$;

drop trigger if exists cashier_requests_updated_at on public.cashier_requests;
create trigger cashier_requests_updated_at before update on public.cashier_requests
for each row execute function public.set_cashier_updated_at();

create table if not exists public.cashier_methods (
  id bigint generated by default as identity primary key,
  method_code text unique not null,
  display_name text not null,
  direction text not null check (direction in ('deposit','withdrawal','both')),
  instructions text not null default '',
  enabled boolean not null default false,
  min_amount numeric(18,2),
  max_amount numeric(18,2),
  currency text not null default 'USD',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.cashier_methods enable row level security;
drop policy if exists "public can read enabled cashier methods" on public.cashier_methods;
create policy "public can read enabled cashier methods" on public.cashier_methods
for select to anon,authenticated using (enabled=true);

insert into public.cashier_methods(method_code,display_name,direction,instructions,enabled,currency)
values
('manual_bank','Manual Bank Transfer','both','Admin will provide the verified bank account instructions. Do not send funds until the account details shown in the cashier are confirmed.',false,'USD'),
('manual_mobile','Manual Mobile Wallet','both','Admin will provide the verified mobile-wallet number and reference format. Keep your transaction receipt.',false,'USD')
on conflict (method_code) do nothing;