-- Payment/reconciliation readiness layer.
-- Stores provider events and financial-operation state without moving money.

create table if not exists public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_event_id text not null,
  event_type text not null,
  signature_verified boolean not null default false,
  idempotency_key text,
  payload_hash text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'received'
    check (status in ('received','verified','processed','ignored','failed')),
  processed_at timestamptz,
  failure_reason text,
  created_at timestamptz not null default now(),
  unique(provider, provider_event_id)
);
create index if not exists payment_webhook_events_status_idx on public.payment_webhook_events(status, created_at);

create table if not exists public.financial_operations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete restrict,
  operation_type text not null check (operation_type in ('deposit','withdrawal','bet_debit','bet_settlement','refund','cashout')),
  source_type text not null check (source_type in ('payment_webhook','cashier_request','bet','admin')),
  source_id text not null,
  idempotency_key text not null,
  amount numeric(18,2) not null check (amount > 0),
  currency text not null,
  status text not null default 'pending'
    check (status in ('pending','authorized','processing','succeeded','failed','reversed','reconciled')),
  provider text,
  provider_reference text,
  wallet_ledger_entry_id bigint references public.wallet_ledger(id) on delete restrict,
  failure_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, idempotency_key)
);
create index if not exists financial_operations_user_time_idx on public.financial_operations(user_id, created_at desc);
create index if not exists financial_operations_status_idx on public.financial_operations(status, created_at);

create table if not exists public.reconciliation_items (
  id bigint generated by default as identity primary key,
  provider text not null,
  provider_reference text not null,
  operation_id uuid references public.financial_operations(id) on delete set null,
  expected_amount numeric(18,2),
  observed_amount numeric(18,2),
  currency text,
  status text not null default 'unmatched'
    check (status in ('unmatched','matched','amount_mismatch','duplicate','manual_review','resolved')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references auth.users(id) on delete set null
);
create unique index if not exists reconciliation_provider_ref_uidx on public.reconciliation_items(provider, provider_reference);

alter table public.payment_webhook_events enable row level security;
alter table public.financial_operations enable row level security;
alter table public.reconciliation_items enable row level security;
revoke all on public.payment_webhook_events from anon, authenticated;
revoke all on public.financial_operations from anon, authenticated;
revoke all on public.reconciliation_items from anon, authenticated;

create or replace function public.set_financial_operation_updated_at()
returns trigger language plpgsql security invoker set search_path=''
as $$ begin new.updated_at=now(); return new; end; $$;
drop trigger if exists financial_operations_updated_at on public.financial_operations;
create trigger financial_operations_updated_at before update on public.financial_operations
for each row execute function public.set_financial_operation_updated_at();
