-- BETNOW365 real-money readiness migration
-- This migration adds compliance state, limits, idempotency, auditability and
-- append-only ledger protections. It intentionally does NOT enable a money-moving
-- bet placement/settlement function.

alter table public.profiles
  add column if not exists kyc_status text not null default 'pending',
  add column if not exists jurisdiction_allowed boolean not null default false,
  add column if not exists responsible_gambling_blocked boolean not null default false,
  add column if not exists betting_limit_daily numeric(18,2),
  add column if not exists betting_limit_weekly numeric(18,2),
  add column if not exists betting_limit_monthly numeric(18,2),
  add column if not exists currency text not null default 'USD',
  add column if not exists compliance_reviewed_at timestamptz;

alter table public.wallets
  add column if not exists status text not null default 'active',
  add column if not exists locked_at timestamptz,
  add column if not exists version bigint not null default 0;

alter table public.bet_quotes
  add column if not exists selection_versions bigint[] not null default '{}',
  add column if not exists currency text not null default 'USD',
  add column if not exists odds_changed boolean not null default false;

alter table public.bets
  add column if not exists currency text not null default 'USD',
  add column if not exists idempotency_key uuid,
  add column if not exists accepted_odds numeric(18,6),
  add column if not exists accepted_at timestamptz,
  add column if not exists settlement_amount numeric(18,2);

create unique index if not exists bets_user_idempotency_uidx
  on public.bets(user_id, idempotency_key)
  where idempotency_key is not null;

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  request_id text,
  ip_hash text,
  user_agent_hash text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_log_actor_time_idx on public.audit_log(actor_user_id, created_at desc);
create index if not exists audit_log_entity_idx on public.audit_log(entity_type, entity_id, created_at desc);
alter table public.audit_log enable row level security;

create table if not exists public.responsible_gambling_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  effective_at timestamptz not null default now(),
  expires_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists rg_events_user_time_idx on public.responsible_gambling_events(user_id, effective_at desc);
alter table public.responsible_gambling_events enable row level security;

drop policy if exists "users can read own responsible gambling events" on public.responsible_gambling_events;
create policy "users can read own responsible gambling events"
  on public.responsible_gambling_events for select
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.prevent_wallet_ledger_mutation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'wallet_ledger is append-only';
end;
$$;

drop trigger if exists wallet_ledger_no_update_delete on public.wallet_ledger;
create trigger wallet_ledger_no_update_delete
before update or delete on public.wallet_ledger
for each row execute function public.prevent_wallet_ledger_mutation();

revoke insert, update, delete on public.wallet_ledger from anon, authenticated;
revoke insert, update, delete on public.audit_log from anon, authenticated;
revoke insert, update, delete on public.responsible_gambling_events from anon, authenticated;
revoke update on public.wallets from anon, authenticated;
revoke insert, update, delete on public.bets from anon, authenticated;
revoke insert, update, delete on public.bet_selections from anon, authenticated;
revoke insert, update, delete on public.bet_quotes from anon, authenticated;

create index if not exists profiles_compliance_idx
  on public.profiles(kyc_status, jurisdiction_allowed, responsible_gambling_blocked);
